### ISSUE TITLE
EACCESS on Linux Mint

### ISSUE THREAD

**Issue by VladimirDev93** [sindresorhus/capture-website-cli#1]
Hey, 

I tried to install the CLI globally, but encountered an issue where npm didn't had the permission to install the package in `/usr/lib/node_modules`. However, after adding the `--unsafe-perm=true` flag to the `sudo npm install --global capture-website-cli --unsafe-perm=true` I was able to install it successfully.

Add it to the docs? or wiki?

**Comment by jneidel** [comment]
Same here (Manjaro Linux), but it works with `--unsafe-perm=true`.

Error output:
```
$ sudo npm i -g capture-website-cli
                                                                                                                     
/usr/bin/capture-website -> /usr/lib/node_modules/capture-website-cli/cli.js                                                                           
                                                                                                                                                       
> puppeteer@1.12.2 install /usr/lib/node_modules/capture-website-cli/node_modules/puppeteer                                                           
> node install.js

ERROR: Failed to download Chromium r624492! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.                                     
{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/capture-website-cli/node_modules/puppeteer/.local-chromium'                          
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/helper.js:108:27)                             
    at Object.<anonymous> (/usr/lib/node_modules/capture-website-cli/node_modules/puppeteer/install.js:64:16)                                         
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)                                                                          
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/lib/node_modules/capture-website-cli/node_modules/puppeteer/.local-chromium' }
```

**Comment by sindresorhus** [comment]
https://www.google.com/search?q=npm+EACCES%3A+permission+denied&oq=npm+EACCES%3A+permission+denied&aqs=chrome..69i57j69i64l2.754j0j1&sourceid=chrome&ie=UTF-8

**Comment by sindresorhus** [comment]
The error has nothing to do with this package specifically. It's an npm install problem. In the future, try to do some simple Googling before opening an issue ;)

For additional support, check out: https://npm.community

**Comment by jneidel** [comment]
> The error has nothing to do with this package specifically.

It's the first time I encountered this problem. All other global installs work without passing `--unsafe-perm=true`.

**Comment by VladimirDev93** [comment]
I know it's not the issue for this package specifically, I was just suggesting that you should add the `--unsafe-perm=true` flag in the docs, for installation.
