### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by cubewebsites** [sindresorhus/capture-website-cli#20]
Using latest version on Ubuntu 18.04

When trying to fetch a URL the script didn't finish running and I had to exit with Ctrl+C. When I did that, the following message was displayed:

```
TimeoutError: Navigation timeout of 30000 ms exceeded
    at Promise.then (/usr/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/usr/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/usr/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/Page.js:675:49)
    at Page.<anonymous> (/usr/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/helper.js:112:23)
    at captureWebsite (/usr/lib/node_modules/capture-website-cli/node_modules/capture-website/index.js:239:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

```
The URL in question does exist and isn't particularly large: 4.52 MB with 30 HTTP requests.

Could you advise on how to fix? Happy to help if you point me in the right direction.

**Comment by david-fanin** [comment]
Hello,
I have the same problem for all the URLs that generates a network error like for example: ERR_NAME_NOT_RESOLVED.

I have to do CTRL + C to get the error messages:

> Error: net::ERR_NAME_NOT_RESOLVED at http://www.site.dom/
    at navigate (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/Page.js:675:49)
    at Page.<anonymous> (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/helper.js:112:23)
    at captureWebsite (/usr/local/lib/node_modules/capture-website-cli/node_modules/capture-website/index.js:233:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by cubewebsites** [comment]
I have a temporary fix for this which is to use the "timeout" command (not the timeout option in capture-website-cli), if you do the following then the process is killed after the timeout period and you can grab the output.  This solves the issue for me although error handling within this package would be better.

`timeout [seconds] capture-website-cli [..your options...]`

**Comment by david-fanin** [comment]
Thanks for the tip! It works well in the meantime.
