### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME error

### ISSUE THREAD

**Issue by aborruso** [sindresorhus/capture-website-cli#32]
Hi,
if I run `capture-website "https://ondata.github.io/vaccinipertutti/?area=SIC" --output=screenshot.png ` I have

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

Thank you

**Comment by aborruso** [comment]
> > Require **Node.js 12.20**

Hi @sindresorhus I have `v14.13.0`. Do I must downgrade my version?

Thank you

**Comment by sindresorhus** [comment]
No, you must upgrade to the latest minor version of v14.

**Comment by aborruso** [comment]
I have 14.13, then greater than 12.20.

Is it not good?

Thank you
