### ISSUE TITLE
Error creating screenshot for specific website

### ISSUE THREAD

**Issue by iComputerfreak** [sindresorhus/capture-website-cli#33]
When executing the following command, I get an error. I tested the command with different URLs and so far this URL is the only one that creates problems for me.

```
username@hostname:~$ capture-website "https://pp.ipd.kit.edu/lehre/SS2021/compiler/uebung" --output="TEST.png"
Error: Evaluation failed: Event
    at ExecutionContext._evaluateInternal (/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DOMWorld.addStyleTag (/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:247:21)
    at async internalCaptureWebsite (file:///home/username/.nvm/versions/node/v14.17.0/lib/node_modules/capture-website-cli/node_modules/capture-website/index.js:244:3)
    at async Object.captureWebsite.file (file:///home/username/.nvm/versions/node/v14.17.0/lib/node_modules/capture-website-cli/node_modules/capture-website/index.js:408:21)
    at async file:///home/username/.nvm/versions/node/v14.17.0/lib/node_modules/capture-website-cli/cli.js:271:3
```

**Comment by sindresorhus** [comment]
This was fixed in a sub-dependency now. Just reinstall this CLI to get it fixed.
